# The Normal Equation Method for minimizing a cost function
For full explanation on what the normal equation method is: 
- https://en.wikipedia.org/wiki/Linear_least_squares_(mathematics)

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression
from sklearn import linear_model

# Generate our random regression data
# We perform destructuring assignment of the output of the make_regression function
# X and y is our training examples where X is the features (i.e. indepdent variables)
# and y is the dependent variable
# coef are the coefficients of the underlying regression model
X, y, coef = make_regression(n_samples=100, n_features=5,
                          n_informative=1, noise=10,
                          coef=True, random_state=0)

X.shape

(100, 5)

In [2]:
y.shape

(100,)

## Let's walkthrough what our implementation should do

Before creating the generalized function, let's walk ourselves through the steps

In [3]:
#n is the number of rows/training examlples
#m is the number of features

n, m = X.shape
print(n, m)

100 5


In [4]:
bias_term = np.ones((n,1)) #create the numpy array that we wanna add on to our matrix
bias_term.shape

(100, 1)

In [5]:
bias_term[:5] #show the first 5 terms, to see that we generated it correctly

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [6]:
new_X = np.append(bias_term, X, axis=1)
new_X[:5] #show first 5 terms to see that we appended it correctly

array([[ 1.        ,  0.14404357,  0.12167502,  1.45427351,  0.44386323,
         0.76103773],
       [ 1.        , -1.18885926, -0.0525673 , -0.50681635, -1.93627981,
        -0.59631404],
       [ 1.        ,  0.91017891, -0.4664191 ,  0.31721822, -0.94444626,
         0.78632796],
       [ 1.        ,  0.52106488, -0.31932842, -0.57578797,  0.69153875,
         0.14195316],
       [ 1.        ,  0.84436298,  1.18802979, -1.00021535,  0.31694261,
        -1.5447711 ]])

In [7]:
new_X.shape #before transposing, let's have a look at the shape

(100, 6)

In [8]:
transposed_X = np.transpose(new_X)
transposed_X.shape

(6, 100)

In [9]:
# Normal Equation:
# theta = inv(X^T * X) * X^T * y

theta = np.linalg.inv(transposed_X.dot(new_X))
print(theta.shape, '\n\n', theta)

(6, 6) 

 [[ 0.01048752  0.00089197  0.00098417  0.00050074 -0.00170268  0.00079259]
 [ 0.00089197  0.01010317 -0.00077568  0.00057676  0.00099198  0.00102299]
 [ 0.00098417 -0.00077568  0.00956155 -0.00049045 -0.0012346  -0.00015461]
 [ 0.00050074  0.00057676 -0.00049045  0.01134685 -0.00152198  0.00127226]
 [-0.00170268  0.00099198 -0.0012346  -0.00152198  0.01118195 -0.00056547]
 [ 0.00079259  0.00102299 -0.00015461  0.00127226 -0.00056547  0.01023688]]


In [10]:
theta = theta.dot(transposed_X)
print(theta.shape, '\n\n', theta)

(6, 100) 

 [[ 1.13114061e-02  1.19457991e-02  1.32305110e-02  9.28474137e-03
   1.01450208e-02  8.18626098e-03  8.07149015e-03  1.33643197e-02
   1.09180746e-02  9.96439181e-03  1.02242841e-02  1.25001070e-02
   6.17294863e-03  8.89071136e-03  1.02051751e-02  9.84776349e-03
   1.29971676e-02  1.42605894e-02  1.02912866e-02  1.05888986e-02
   9.50791104e-03  5.72035632e-03  1.19789352e-02  1.05776529e-02
   1.06235842e-02  1.22122767e-02  9.66856567e-03  9.17089596e-03
   1.02222702e-02  8.85954547e-03  1.15697409e-02  8.84918234e-03
   1.05165157e-02  1.16018464e-02  1.12595101e-02  4.78029597e-03
   7.39633346e-03  6.95236285e-03  8.69214412e-03  1.12269991e-02
   1.01530510e-02  8.69824283e-03  9.92940801e-03  1.21216477e-02
   1.20627012e-02  7.85223623e-03  1.04452328e-02  1.11359747e-02
   1.27092606e-02  1.34368923e-02  1.05995865e-02  7.06210208e-03
   1.05929190e-02  1.21914972e-02  9.61905641e-03  6.22245106e-03
   9.55898118e-03  9.95103351e-03  1.11340633e-02  1.07007176e-0

In [11]:
theta = theta.dot(y)
print(theta.shape, '\n\n', theta)


(6,) 

 [-2.07384225e+00  4.58448502e+01 -8.45538675e-03 -2.38412637e+00
  5.91382877e-01 -6.86280983e-01]


## Let's create the generalized normal equation

In [12]:


def normal_equation(X, y):
    """
        Normal Equation:
        theta = inv(X^T * X) * X^T * y
        
        In this implementation, m refers to the number of features, and n refers to the number of training examples
        
        args:
            X: refers to the independent variables, a numpy matrix, n x m matrix
            y:  refers to the dependent variables, a numpy matrix. , n x 1 matrix 
        returns:
            theta: the minima
    """
    n, m = X.shape
    # We need to add on our bias term
    bias_term = np.ones((n, 1))
    new_X = np.append(bias_term, X, axis=1)  #we avoid mutating our original input, X
    # we need to reshape our training data into a "m x (n+1)" matrix
    
    #we need to transpose our matrix
    transposed_X = np.transpose(new_X)
    
    # Calculating theta
    theta = np.linalg.inv(transposed_X.dot(new_X))
    theta = theta.dot(transposed_X)
    theta = theta.dot(y)
    
    # X = np.reshape(X, (m, 1))
    return theta
normal_equation(X,y)

array([-2.07384225e+00,  4.58448502e+01, -8.45538675e-03, -2.38412637e+00,
        5.91382877e-01, -6.86280983e-01])

In [13]:
X1, y1, coef1 = make_regression(n_samples=100, n_features=500,
                          n_informative=1, noise=10,
                          coef=True, random_state=0)

# Not recommended to try to time above 5000 features, unless you want to risk your computer crashing.
X2, y2, coef2 = make_regression(n_samples=100, n_features=1000,
                          n_informative=1, noise=10,
                          coef=True, random_state=0)


In [14]:
import timeit

if __name__=='__main__':
    t = timeit.timeit(lambda: normal_equation(X,y), number=1)
    print("for 5 features: ", t)

    t = timeit.timeit(lambda: normal_equation(X1,y1), number=1)
    print("for 500 features: ", t)

    t = timeit.timeit(lambda: normal_equation(X2,y2), number=1)
    print("for 1000 features: ", t)

for 5 features:  0.0003744229999824711
for 500 features:  0.055763610999974844
for 1000 features:  0.11512813199999528
